base:
    # Environment configs
    output_path: "exps/cpp_state_corruption"
    benchmark: "cpp"
    problems: ["state_corruption_debug"]
    env_kwargs: 
        source_path: "buggy_cpp_samples/state_corruption"
        entrypoint: "./state_corruption"
        debug_entrypoint: "gdb ./state_corruption"
        dir_tree_depth: 2
        run_timeout: 45
        show_directory_tree: true

    # LLM configs  
    llm_name: "gpt-4o-mini-fast"

    # Agent configs
    random_seed: 42
    max_steps: 25
    max_rewrite_steps: 18
    memory_size: 50
    save_patch: true

debug_agent_cpp:
    tools: ["gdb", "view", "rewrite", "eval"]