base:
    # Environment configs
    output_path: "exps/cpp_data_structure_bugs"
    benchmark: "cpp"
    problems: ["data_structure_debug"]
    env_kwargs: 
        source_path: "buggy_cpp_samples/data_structure_bugs"
        entrypoint: "./data_structure_bugs"
        debug_entrypoint: "gdb ./data_structure_bugs"
        dir_tree_depth: 2
        run_timeout: 60
        show_directory_tree: true

    # LLM configs  
    llm_name: "gpt-4o-mini-fast"

    # Agent configs
    random_seed: 42
    max_steps: 30
    max_rewrite_steps: 20
    memory_size: 60
    save_patch: true

debug_agent_cpp:
    tools: ["gdb", "view", "rewrite", "eval"]