base:
    # Environment configs
    output_path: "exps/cpp_null_pointer"
    benchmark: "cpp"
    problems: ["null_pointer_demo"]
    env_kwargs:
        source_path: "buggy_cpp_samples/null_pointer"
        entrypoint: "./null_deref"
        debug_entrypoint: "./null_deref"
        dir_tree_depth: 2
        run_timeout: 30
        show_directory_tree: true

    # LLM configs  
    llm_name: "gpt-4o-mini-fast"

    # Agent configs
    random_seed: 42
    max_steps: 15
    max_rewrite_steps: 10
    memory_size: 30
    save_patch: true

cpp_debug_agent:
    tools: ["gdb", "view", "rewrite", "eval"]