base:
    # Environment configs
    output_path: "exps/cpp_auto_debug"
    benchmark: "cpp"
    problems: ["custom"]
    env_kwargs: {
        "entrypoint": "./buffer_bug",
        "debug_entrypoint": "gdb ./buffer_bug",
        "dir_tree_depth": 2,
        "run_timeout": 30,
        "show_directory_tree": true,
    }

    # LLM configs  
    llm_name: "gpt-4o-mini-fast"

    # Agent configs
    random_seed: 42
    max_steps: 15
    max_rewrite_steps: 10
    memory_size: 30
    save_patch: true

debug_agent_cpp:
    tools: ["gdb", "view", "rewrite", "eval"]